//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Skills
    {
        public int ID { get; set; }
        public string skill { get; set; }
        public Nullable<byte> rate { get; set; }
    }
}
